config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :manifesto_promises

    root 'manifesto_promises#index'

end

app/models/manifesto_promise.rb
class ManifestoPromise < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/manifesto_promises_controller.rb
class ManifestoPromisesController < ApplicationController
  before_action :set_manifesto_promise, only: [:show, :edit, :update, :destroy]

  # GET /manifesto_promises
  # GET /manifesto_promises.json
  def index
    @manifesto_promises = ManifestoPromise.all
  end

  # GET /manifesto_promises/1
  # GET /manifesto_promises/1.json
  def show
  end

  # GET /manifesto_promises/new
  def new
    @manifesto_promise = ManifestoPromise.new
  end

  # GET /manifesto_promises/1/edit
  def edit
  end

  # POST /manifesto_promises
  # POST /manifesto_promises.json
  def create
    @manifesto_promise = ManifestoPromise.new(manifesto_promise_params)

    respond_to do |format|
      if @manifesto_promise.save
        format.html { redirect_to @manifesto_promise, notice: 'Manifesto promise was successfully created.' }
        format.json { render :show, status: :created, location: @manifesto_promise }
      else
        format.html { render :new }
        format.json { render json: @manifesto_promise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manifesto_promises/1
  # PATCH/PUT /manifesto_promises/1.json
  def update
    respond_to do |format|
      if @manifesto_promise.update(manifesto_promise_params)
        format.html { redirect_to @manifesto_promise, notice: 'Manifesto promise was successfully updated.' }
        format.json { render :show, status: :ok, location: @manifesto_promise }
      else
        format.html { render :edit }
        format.json { render json: @manifesto_promise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifesto_promises/1
  # DELETE /manifesto_promises/1.json
  def destroy
    @manifesto_promise.destroy
    respond_to do |format|
      format.html { redirect_to manifesto_promises_url, notice: 'Manifesto promise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manifesto_promise
      @manifesto_promise = ManifestoPromise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manifesto_promise_params
      params.require(:manifesto_promise).permit(:title, :description, :progress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manifesto_promises_helper.rb
module ManifestoPromisesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manifesto_promises/_form.html.erb
<%= form_for(@manifesto_promise) do |f| %>
  <% if @manifesto_promise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manifesto_promise.errors.count, "error") %> prohibited this manifesto_promise from being saved:</h2>

      <ul>
      <% @manifesto_promise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :progress %><br>
    <%= f.text_field :progress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manifesto_promises/edit.html.erb
<h1>Editing Manifesto Promise</h1>

<%= render 'form' %>

<%= link_to 'Show', @manifesto_promise %> |
<%= link_to 'Back', manifesto_promises_path %>

app/views/manifesto_promises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manifesto Promises</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Progress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manifesto_promises.each do |manifesto_promise| %>
      <tr>
        <td><%= manifesto_promise.title %></td>
        <td><%= manifesto_promise.description %></td>
        <td><%= manifesto_promise.progress %></td>
        <td><%= link_to 'Show', manifesto_promise %></td>
        <td><%= link_to 'Edit', edit_manifesto_promise_path(manifesto_promise) %></td>
        <td><%= link_to 'Destroy', manifesto_promise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manifesto promise', new_manifesto_promise_path %>

app/views/manifesto_promises/new.html.erb
<h1>New Manifesto Promise</h1>

<%= render 'form' %>

<%= link_to 'Back', manifesto_promises_path %>

app/views/manifesto_promises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @manifesto_promise.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @manifesto_promise.description %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @manifesto_promise.progress %>
</p>

<%= link_to 'Edit', edit_manifesto_promise_path(@manifesto_promise) %> |
<%= link_to 'Back', manifesto_promises_path %>